#!/bin/bash

# Base directories
NS3_DIR="$HOME/ns3-mmwave"
DATASET_DIR="$HOME/dataset/nonattack"

# Create dataset directory if it doesn't exist
mkdir -p "$DATASET_DIR"

# Create parameter log file with header
PARAM_LOG="$DATASET_DIR/simulation_parameters.csv"
echo "test_case,n,ue_posn,ue_vel" > "$PARAM_LOG"

# Function to generate UE positions and velocities
generate_parameters() {
    local testcase=$1
    
    local n=$(( (testcase % 9) + 2 ))  # This ensures n is always btw 2-10
    local posn=""
    local vel=""
    
    for (( i=0; i<n; i++ )); do
        local x=$(( (RANDOM % 100) - 50 ))
        local y=$(( (RANDOM % 100) - 50 ))
        local z=0
        local vx=$(( (RANDOM % 20) - 10 ))
        local vy=$(( (RANDOM % 20) - 10 ))
        local vz=0
        
        posn+="$x,$y,$z"
        vel+="$vx,$vy,$vz"
        
        if (( i < n-1 )); then
            posn+=","
            vel+=","
        fi
    done
    
    echo "$n $posn $vel"
}

# Main loop for 450 test cases
for (( i=1; i<=550; i++ )); do
    echo "Processing Test Case $i..."
    
    # Generate parameters for this test case
    read -r n posn vel <<< $(generate_parameters $i)
    
    # Log parameters to CSV
    echo "$i,$n,\"$posn\",\"$vel\"" >> "$PARAM_LOG"
    
    # Create test case directory
    TC_DIR="$DATASET_DIR/TC$i"
    mkdir -p "$TC_DIR"
    
    # Change to ns3 directory
    cd "$NS3_DIR" || exit 1
    
    # Step 1: Run uav8_automated.cc with generated parameters
    echo "Running simulation with n=$n, posn=$posn, vel=$vel"
    ./ns3 run "uav8_automated.cc --n=$n --ue_posn=$posn --ue_vel=$vel"
    
    # Step 2: Run RxParser with current n value
    echo "Running RxParser with n=$n..."
    ./Rx_parser_generalized $n
    
    # Step 3: Move result files to test case directory
    echo "Moving result files to $TC_DIR"
    
    # Move RSSI files
    for (( ue=1; ue<=n; ue++ )); do
        mv "UE${ue}_rssi.csv" "$TC_DIR/" 2>/dev/null
    done
    
    # Move SINR files (generated by RxParser)
    for (( ue=1; ue<=n; ue++ )); do
        if [ -f "UE${ue}_sinr.csv" ]; then
            mv "UE${ue}_sinr.csv" "$TC_DIR/"
        fi
    done
    
    # Move RxPacketTrace.txt
    mv "RxPacketTrace.txt" "$TC_DIR/" 2>/dev/null
    
    echo "Completed Test Case $i"
    echo "----------------------------------"
done

echo "All 550 test cases processed successfully!"
echo "Parameter log saved to: $PARAM_LOG"